"""resume versions and tags

Revision ID: 0f1d7d82a89f
Revises: 4c05b3bebb36
Create Date: 2026-07-24 00:19:17.154426
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0f1d7d82a89f'
down_revision: str | None = '4c05b3bebb36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_profile_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_profile_id'], ['resume_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_profile_id', 'version', name='uq_resume_version_profile_version')
    )
    op.create_index(op.f('ix_resume_versions_resume_profile_id'), 'resume_versions', ['resume_profile_id'], unique=False)
    # NOT NULL additions get a server_default so existing résumé rows backfill
    # (empty tag list, version 1), then the default is dropped so new rows come
    # from the application defaults instead.
    op.add_column(
        'resume_profiles',
        sa.Column(
            'tags',
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.add_column(
        'resume_profiles',
        sa.Column('current_version', sa.Integer(), nullable=False, server_default='1'),
    )
    op.alter_column('resume_profiles', 'tags', server_default=None)
    op.alter_column('resume_profiles', 'current_version', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_profiles', 'current_version')
    op.drop_column('resume_profiles', 'tags')
    op.drop_index(op.f('ix_resume_versions_resume_profile_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    # ### end Alembic commands ###
