"""resume template field

Revision ID: 5fd6342d87c0
Revises: bc7b3588ad44
Create Date: 2026-07-24 00:53:32.114625
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5fd6342d87c0'
down_revision: str | None = 'bc7b3588ad44'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing résumés backfill to the default "modern" template.
    op.add_column(
        'resume_profiles',
        sa.Column('template', sa.String(length=20), nullable=False, server_default='modern'),
    )
    op.alter_column('resume_profiles', 'template', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_profiles', 'template')
    # ### end Alembic commands ###
