"""writing profile and samples

Revision ID: bc7b3588ad44
Revises: 0f1d7d82a89f
Create Date: 2026-07-24 00:25:19.472526
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bc7b3588ad44'
down_revision: str | None = '0f1d7d82a89f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writing_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voice', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_profiles_user_id'), 'writing_profiles', ['user_id'], unique=True)
    op.create_table('writing_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('writing_profile_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('COVER_LETTER', 'EMAIL', 'SOP', 'OTHER', name='writing_sample_kind', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['writing_profile_id'], ['writing_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_samples_writing_profile_id'), 'writing_samples', ['writing_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_writing_samples_writing_profile_id'), table_name='writing_samples')
    op.drop_table('writing_samples')
    op.drop_index(op.f('ix_writing_profiles_user_id'), table_name='writing_profiles')
    op.drop_table('writing_profiles')
    # ### end Alembic commands ###
